POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbG8iLCJpZCI6IjY1YmEzZGNkMmU5M2QwZjM1NWU3MmU3ZCIsImlhdCI6MTcwNjg0OTg2Nn0._p4J22cmYUUOxQ-HuGpDXtR1afq-OnErpm-IKqvmK3Y

{
    "content": "This is becoming a pain in the ass",
    "important": true
}